/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/MISC4_shit.glb --transform 
Files: ./public/MISC4_shit.glb [334.15KB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/MISC4_shit-transformed.glb [15.18KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/MISC4_shit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.009']} position={[1.189, -3.389, 1.541]} />
    </group>
  )
}

useGLTF.preload('/MISC4_shit-transformed.glb')
