/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Seen_low_2K.glb --transform 
Files: ./public/Seen_low_2K.glb [16.62MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/Seen_low_2K-transformed.glb [3.82MB] (77%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { NodeToyMaterial, NodeToyTick } from "@nodetoy/react-nodetoy";

export function Sniker(props) {
  const { nodes, materials } = useGLTF(
    "src/models/Seen_low_2K-transformed.glb"
  );

  console.log("nodes", nodes);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Backdrop_02_low.geometry}
        position={[0.116, 0.057, 0.17]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <NodeToyMaterial url={"https://draft.nodetoy.co/RSRga1MkicIaakYM"} />
      </mesh>
      <mesh
        geometry={nodes.Backdrop_02_low_2.geometry}
        material={materials.Seen_R}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("src/models/Seen_low_2K-transformed.glb");
