/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/CD_header_v1.glb --transform 
Files: ./public/CD_header_v1.glb [3.21MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/index_page/cd25_website/CD_header_v1-transformed.glb [188.13KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CD_header_v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gold_International.geometry} material={materials.gold} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.WhiteFont_OnTop.geometry} material={materials.white} position={[-0.261, 0.058, 0.004]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/CD_header_v1-transformed.glb')
