/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/FontWorkWebpage.glb --transform 
Files: ./public/FontWorkWebpage.glb [9.5MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/index_page/cd25_website/FontWorkWebpage-transformed.glb [193.85KB] (98%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export function NewFont(props) {
  const { nodes, materials } = useGLTF(
    "src/models/FontWorkWebpage-transformed.glb"
  );

  const textMaterials = new THREE.MeshStandardMaterial({
    color: "gold",
    roughness: 0.1,
    metalness: 0.8,
    emissive: "black",
    emissiveIntensity: 0.5,
  });

  materials.gold = textMaterials;
  return (
    <group {...props} dispose={null}>
      {/* <mesh
        geometry={nodes.WhiteFont_OnTop.geometry}
        material={materials.white}
        position={[0, -0.011, 0]}
      /> */}
      <mesh
        geometry={nodes.GoldFont_Underneath.geometry}
        material={materials.gold}
        position={[0, -0.011, 0]}
      />
    </group>
  );
}

useGLTF.preload("src/models/FontWorkWebpage-transformed.glb");
