/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/KreatonUV1.glb --transform 
Files: ./public/KreatonUV1.glb [9.99MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/KreatonUV1-transformed.glb [263.47KB] (97%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "src/models/KreatonUV1-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  console.log(nodes);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Arms001">
          <mesh
            name="Armsmesh"
            geometry={nodes.Armsmesh.geometry}
            material={materials.white}
          />
          <mesh
            name="Armsmesh_1"
            geometry={nodes.Armsmesh_1.geometry}
            material={materials.gold}
          />
          <mesh
            name="Armsmesh_2"
            geometry={nodes.Armsmesh_2.geometry}
            material={materials.Skin}
          />
        </group>
        <group name="TorsoArmor001">
          <mesh
            name="TorsoArmormesh"
            geometry={nodes.TorsoArmormesh.geometry}
            material={materials.white}
          />
          <mesh
            name="TorsoArmormesh_1"
            geometry={nodes.TorsoArmormesh_1.geometry}
            material={materials.gold}
          />
          <mesh
            name="TorsoArmormesh_2"
            geometry={nodes.TorsoArmormesh_2.geometry}
            material={materials.Skin}
          />
        </group>
        <group
          name="Helmet_UNATTACHED001"
          position={[0.033, -0.015, -0.044]}
          rotation={[0.016, -0.038, 0.031]}
        >
          <mesh
            name="HelmetFacemesh003"
            geometry={nodes.HelmetFacemesh003.geometry}
            material={materials.white}
          />
          <mesh
            name="HelmetFacemesh003_1"
            geometry={nodes.HelmetFacemesh003_1.geometry}
            material={materials.gold}
          />
          <mesh
            name="HelmetFacemesh003_2"
            geometry={nodes.HelmetFacemesh003_2.geometry}
            material={materials.Skin}
          />
          <mesh
            name="HelmetFacemesh003_3"
            geometry={nodes.HelmetFacemesh003_3.geometry}
            material={materials.Tail}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("src/models/KreatonUV1-transformed.glb");
