/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/CD_header_v1.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Header_v1(props) {
  const { nodes, materials } = useGLTF("src/models/CD_header_v1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Gold_International.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD002.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD004.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD016.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD019.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD020.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD023.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD028.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD029.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD030.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD032.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD037.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD045.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD055.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_CD059.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International002.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International003.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International004.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International005.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International006.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International007.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International008.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International009.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International010.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International011.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International012.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International013.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International015.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International016.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International017.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International019.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International021.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International022.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International023.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International024.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International026.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International040.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International074.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International076.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Gold_International082.geometry}
        material={materials.gold}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.R_big.geometry}
        material={materials["gold.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.R_small1.geometry}
        material={materials["gold.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.R_small2.geometry}
        material={materials["gold.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop.geometry}
        material={materials.white}
        position={[-0.261, 0.058, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop001.geometry}
        material={materials.white}
        position={[-0.032, 0.015, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop028.geometry}
        material={materials.white}
        position={[-0.269, 0.015, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop029.geometry}
        material={materials.white}
        position={[-0.217, 0.015, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop030.geometry}
        material={materials.white}
        position={[-0.161, 0.017, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop031.geometry}
        material={materials.white}
        position={[-0.094, 0.011, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop033.geometry}
        material={materials.white}
        position={[0.029, 0.018, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop034.geometry}
        material={materials.white}
        position={[0.092, 0.015, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop035.geometry}
        material={materials.white}
        position={[0.154, 0.017, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop036.geometry}
        material={materials.white}
        position={[0.214, 0.015, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop037.geometry}
        material={materials.white}
        position={[-0.182, 0.062, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop038.geometry}
        material={materials.white}
        position={[-0.106, 0.075, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop040.geometry}
        material={materials.white}
        position={[-0.03, 0.057, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop041.geometry}
        material={materials.white}
        position={[0.029, 0.065, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop042.geometry}
        material={materials.white}
        position={[0.075, 0.058, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop043.geometry}
        material={materials.white}
        position={[0.121, 0.059, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.WhiteFont_OnTop045.geometry}
        material={materials.white}
        position={[0.197, 0.05, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH001.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH002.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH003.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH004.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH005.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH006.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH007.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH008.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH009.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH010.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH011.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH012.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH013.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH014.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH015.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH016.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH017.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH018.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH019.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH020.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH021.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH022.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH023.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH024.geometry}
        material={materials.white}
      />
      <mesh
        geometry={nodes.OriginalCurveInternationalWHITE_MESH025.geometry}
        material={materials.white}
      />
    </group>
  );
}

useGLTF.preload("src/models/CD_header_v1.glb");
