/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/CD_header_v1.glb 
*/

import React, {
  forwardRef,
  useRef,
  useImperativeHandle,
  useMemo,
  useEffect,
} from "react";
import { useGLTF, useHelper } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import * as THREE from "three";
import { useModelLoader, preloadModel } from "../utils/ModelLoader";
import { GoldMaterial } from "../materials/globalGoldMaterial";
import { WhiteMaterial } from "../materials/globalWhiteMaterial";

// Define model URLs
const localModelUrl = "src/models/CD_header_v1-transformed.glb";
const remoteModelUrl = "https://files.creative-directors.com/creative-website/creative25/glbs/CD_header_v1-transformed.glb";
const DEBUG_LOGS = process.env.NODE_ENV === 'development';



// Individual material constants for easy tweaking
const headerGoldMaterial = GoldMaterial;
const headerWhiteMaterial = WhiteMaterial;

const Header_v1 = forwardRef((props, ref) => {
  const { nodes, materials } = useModelLoader(localModelUrl, remoteModelUrl);
  const groupRef = useRef();
  const goldMeshRefs = useRef([]);
  const whiteMeshRefs = useRef([]);
  const goldOriginalRotations = useRef([]);
  const whiteOriginalRotations = useRef([]);
  const pointLightRef = useRef();
  const timeRef = useRef(0);

  // Add point light helper
  // useHelper(pointLightRef, THREE.PointLightHelper, 0.5, "#ffffff");

  // Animate point light to orbit around origin using useFrame
  useFrame((state, delta) => {
    if (pointLightRef.current) {
      timeRef.current += delta;
      const radius = 0.1;
      const speed = 0.8;
      pointLightRef.current.position.x = Math.cos(timeRef.current * speed) * radius * 3;
      pointLightRef.current.position.y = 0.05 + Math.sin(timeRef.current * speed) * radius * 0.5;
      pointLightRef.current.position.z = 0; // Keep y constant
    }
  });

  // Memoize keys to prevent re-filtering on every render
  const goldKeys = useMemo(
    () => Object.keys(nodes).filter((key) => key.startsWith("Gold_") || key.startsWith("R_")),
    [nodes]
  );

  const whiteKeys = useMemo(
    () => Object.keys(nodes).filter(
      (key) =>
        key.startsWith("WhiteFont_") ||
        key.startsWith("OriginalCurveInternationalWHITE_")
    ),
    [nodes]
  );

  // Use GSAP's context-aware hook for safer animation management and cleanup
  useGSAP(() => {
    if (DEBUG_LOGS) {
      console.log("[Header_v1] goldKeys:", goldKeys);
      console.log("[Header_v1] whiteKeys:", whiteKeys);
    }

    // Wait until all refs are populated
    const allGoldRefsReady = goldMeshRefs.current.length === goldKeys.length && goldMeshRefs.current.every(Boolean);
    const allWhiteRefsReady = whiteMeshRefs.current.length === whiteKeys.length && whiteMeshRefs.current.every(Boolean);

    if (!allGoldRefsReady || !allWhiteRefsReady) {
      if (DEBUG_LOGS) console.log("[Header_v1] Not all mesh refs are ready. Skipping animation setup.");
      return;
    }

    if (DEBUG_LOGS) console.log("[Header_v1] All mesh refs are ready. Starting animation setup.");

    // Store original rotations
    goldOriginalRotations.current = goldKeys.map((key) => nodes[key].rotation || new THREE.Euler());
    whiteOriginalRotations.current = whiteKeys.map((key) => nodes[key].rotation || new THREE.Euler());

    // Set initial state
    const allMeshes = [...goldMeshRefs.current, ...whiteMeshRefs.current];
    gsap.set(allMeshes.map(m => m.scale), { x: 0, y: 0, z: 0 });

    goldMeshRefs.current.forEach((mesh, i) => {
      const originalRotation = goldOriginalRotations.current[i];
      gsap.set(mesh.rotation, { y: originalRotation.y + Math.PI * 2 });
    });

    whiteMeshRefs.current.forEach((mesh, i) => {
      const originalRotation = whiteOriginalRotations.current[i];
      gsap.set(mesh.rotation, { y: originalRotation.y - Math.PI * 2 });
    });

    // Animate in with stagger
    gsap.to(allMeshes.map(m => m.scale), {
      x: 1,
      y: 1,
      z: 1,
      duration: 0.7,
      ease: "bounce.out",
      stagger: 0.1,
      onStart: () => DEBUG_LOGS && console.log(`[Header_v1] Animating mesh scale in (bounce staggered)`),
      onComplete: () => DEBUG_LOGS && console.log(`[Header_v1] Mesh scale animation complete (bounce staggered)`),
    });

  }, { dependencies: [nodes, goldKeys, whiteKeys], scope: groupRef });

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      // Kill any GSAP tweens targeting this component's meshes
      if (goldMeshRefs.current.length > 0) {
        gsap.killTweensOf(goldMeshRefs.current);
      }
      if (whiteMeshRefs.current.length > 0) {
        gsap.killTweensOf(whiteMeshRefs.current);
      }
      if (groupRef.current) {
        gsap.killTweensOf(groupRef.current);
      }

      if (DEBUG_LOGS) {
        console.log("🧹 Header cleanup complete");
      }
    };
  }, []);

  // Expose animation controls to parent component
  useImperativeHandle(ref, () => ({
    playAnimation: () => {
      if (DEBUG_LOGS) console.log("[Header_v1] playAnimation called");
      // Replay the show animation
      const allMeshes = [...goldMeshRefs.current, ...whiteMeshRefs.current].filter(Boolean);
      gsap.to(allMeshes.map(m => m.scale), {
        x: 1, y: 1, z: 1, duration: 0.8, ease: "elastic.out(1, 0.5)", stagger: 0.1
      });
      gsap.to(goldMeshRefs.current.filter(Boolean).map((m, i) => m.rotation), {
        y: (i) => goldOriginalRotations.current[i]?.y || 0, duration: 0.8, ease: "power2.out", stagger: 0.1
      });
      gsap.to(whiteMeshRefs.current.filter(Boolean).map((m, i) => m.rotation), {
        y: (i) => whiteOriginalRotations.current[i]?.y || 0, duration: 0.8, ease: "power2.out", stagger: 0.1
      });
    },
    reverseAnimation: () => {
      if (DEBUG_LOGS) console.log("[Header_v1] reverseAnimation called");
      // Animate all letters out (scale to 0)
      const allMeshes = [...goldMeshRefs.current, ...whiteMeshRefs.current].filter(Boolean);
      gsap.to(allMeshes.map(m => m.scale), {
        x: 0, y: 0, z: 0, duration: 0.5, ease: "power2.in", stagger: 0.05
      });
    },
    hide: () => {
      if (DEBUG_LOGS) console.log("[Header_v1] hide called");
      const allMeshes = [...goldMeshRefs.current, ...whiteMeshRefs.current].filter(Boolean);
      gsap.to(allMeshes.map(m => m.scale), {
        x: 0, y: 0, z: 0, duration: 0.3, ease: "power2.in", stagger: 0.05
      });
    },
    show: () => {
      if (DEBUG_LOGS) console.log("[Header_v1] show called");
      // Show with staggered effect
      const allMeshes = [...goldMeshRefs.current, ...whiteMeshRefs.current].filter(Boolean);
      gsap.to(allMeshes.map(m => m.scale), {
        x: 1, y: 1, z: 1, duration: 0.8, ease: "elastic.out(1, 0.5)", stagger: 0.1
      });
    },
    moveUp: (y = 1) => {
      if (groupRef.current) {
        if (DEBUG_LOGS) console.log(`[Header_v1] moveUp called with y=${y}`);
        gsap.to(groupRef.current.position, {
          y: groupRef.current.position.y + y,
          duration: 1.2,
          ease: "power2.out"
        });
      }
    },
    resetAnimation: () => {
      if (DEBUG_LOGS) console.log("[Header_v1] resetAnimation called");
      // Instantly reset all letters to initial state
      goldMeshRefs.current.forEach((mesh, i) => {
        if (mesh) {
          const originalRotation = goldOriginalRotations.current[i] || { x: 0, y: 0, z: 0 };
          mesh.scale.set(0, 0, 0);
          mesh.rotation.set(
            originalRotation.x,
            originalRotation.y + Math.PI * 2,
            originalRotation.z
          );
        }
      });
      whiteMeshRefs.current.forEach((mesh, i) => {
        if (mesh) {
          const originalRotation = whiteOriginalRotations.current[i] || { x: 0, y: 0, z: 0 };
          mesh.scale.set(0, 0, 0);
          mesh.rotation.set(
            originalRotation.x,
            originalRotation.y - Math.PI * 2,
            originalRotation.z
          );
        }
      });
      if (groupRef.current) {
        gsap.set(groupRef.current.position, { y: 0 });
      }
    },
    getGroupRef: () => groupRef.current,
  }));

  // Render all meshes and collect refs
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <pointLight ref={pointLightRef} intensity={5} color={"#ffffff"} />

      {goldKeys.map((key, i) => (
        <mesh
          key={key}
          ref={(el) => (goldMeshRefs.current[i] = el)}
          geometry={nodes[key].geometry}
          material={headerGoldMaterial}
          position={nodes[key].position}
          rotation={nodes[key].rotation}
        />
      ))}

      {whiteKeys.map((key, i) => (
        <mesh
          key={key}
          ref={(el) => (whiteMeshRefs.current[i] = el)}
          geometry={nodes[key].geometry}
          material={headerWhiteMaterial}
          rotation={nodes[key].rotation}
          position={nodes[key].position}
        />
      ))}
    </group>
  );
});

preloadModel(localModelUrl, remoteModelUrl);

export { Header_v1 };
export default Header_v1;
