/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/earthv4_UV.glb --transform
Files: ./public/earthv4_UV.glb [356.76KB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/earthv4_UV-transformed.glb [30.93KB] (91%)
*/

import React, { useRef, useMemo, useEffect, useCallback } from "react";
import { useGLTF, useTexture, shaderMaterial, Sphere } from "@react-three/drei";
import { useFrame, extend, useThree } from "@react-three/fiber";
import * as THREE from "three";
import { Suspense } from "react";
import { forwardRef, useImperativeHandle } from "react";
import { useControls } from "leva";
import {
  Color,
  RepeatWrapping,
  DoubleSide,
  LinearMipmapLinearFilter,
} from "three";
import { useModelLoader, preloadModel } from "../utils/ModelLoader";

// Determine the model URL based on the environment
const isDevelopment = process.env.NODE_ENV === 'development';
const localModelUrl = "src/models/earth_final-transformed.glb";
const remoteModelUrl =
  "https://files.creative-directors.com/creative-website/creative25/glbs/earth_final-transformed.glb";
const modelUrl = isDevelopment ? localModelUrl : remoteModelUrl;

// const localWaterTextureUrl = "/water-texture_Small.jpeg";
const localWaterTextureUrl = "/ocean_diffuse.jpg";
// const localWaterTextureUrl = "/texture_stylized_water.png";


// const remoteWaterTextureUrl =
//   "http://files.creative-directors.com/creative-website/creative25/textures/water-texture_Small.jpeg";

const remoteWaterTextureUrl =
  "https://files.creative-directors.com/creative-website/creative25/textures/ocean_diffuse.jpg";

const waterTextureUrl = isDevelopment
  ? localWaterTextureUrl
  : remoteWaterTextureUrl;

// Only log in development
if (isDevelopment) {
  console.log(`Loading water texture from: ${waterTextureUrl}`);
  console.log(`Loading model from: ${modelUrl}`);
}

// Water texture repeat multiplier constant
const WATER_TEXTURE_REPEAT_MULTIPLIER = 2.0;

// Extract shaders to constants for better readability and to avoid re-creation
const WATER_VERTEX_SHADER = `
  uniform float uTime;
  uniform float uNoiseFrequency;
  uniform float uNoiseAmplitude;
  uniform float uNoiseSpeed;

  varying vec2 vUv;
  varying vec3 vWorldPosition;
  varying vec3 vWorldNormal;

  // Simplex 3D noise
  vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
  vec4 mod289(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
  vec4 permute(vec4 x) { return mod289(((x*34.0)+1.0)*x); }
  vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.853734720909014 * r; }

  float snoise(vec3 v) {
    const vec2 C = vec2(1.0/6.0, 1.0/3.0) ;
    const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);
    vec3 i  = floor(v + dot(v, C.yyy) );
    vec3 x0 = v - i + dot(i, C.xxx) ;
    vec3 g = step(x0.yzx, x0.xyz);
    vec3 l = 1.0 - g;
    vec3 i1 = min( g.xyz, l.zxy );
    vec3 i2 = max( g.xyz, l.zxy );
    vec3 x1 = x0 - i1 + C.xxx;
    vec3 x2 = x0 - i2 + C.yyy;
    vec3 x3 = x0 - D.yyy;
    i = mod289(i);
    vec4 p = permute( permute( permute(
              i.z + vec4(0.0, i1.z, i2.z, 1.0 ))
            + i.y + vec4(0.0, i1.y, i2.y, 1.0 ))
            + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));
    float n_ = 0.142857142857; // 1.0/7.0
    vec3 ns = n_ * D.wyz - D.xzx;
    vec4 j = p - 49.0 * floor(p * ns.z * ns.z);
    vec4 x_ = floor(j * ns.z);
    vec4 y_ = floor(j - 7.0 * x_ );
    vec4 x = x_ *ns.x + ns.yyyy;
    vec4 y = y_ *ns.x + ns.yyyy;
    vec4 h = 1.0 - abs(x) - abs(y);
    vec4 b0 = vec4( x.xy, y.xy );
    vec4 b1 = vec4( x.zw, y.zw );
    vec4 s0 = floor(b0)*2.0 + 1.0;
    vec4 s1 = floor(b1)*2.0 + 1.0;
    vec4 sh = -step(h, vec4(0.0));
    vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;
    vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww ;
    vec3 p0 = vec3(a0.xy,h.x);
    vec3 p1 = vec3(a0.zw,h.y);
    vec3 p2 = vec3(a1.xy,h.z);
    vec3 p3 = vec3(a1.zw,h.w);
    vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2,p2), dot(p3,p3)));
    p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w;
    vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);
    m = m * m;
    return 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3) ) );
  }

  void main() {
    vUv = uv;

    // Use uniforms for noise properties
    float displacement = snoise(position * uNoiseFrequency + uTime * uNoiseSpeed) * uNoiseAmplitude;
    displacement += snoise(position * uNoiseFrequency * 2.5 + uTime * uNoiseSpeed * 1.5) * uNoiseAmplitude * 0.5;

    vec3 newPosition = position - normal * displacement; // Inverted displacement

    // Calculate world position and normal for reflection
    vec4 worldPosition = modelMatrix * vec4(newPosition, 1.0);
    vWorldPosition = worldPosition.xyz;
    vWorldNormal = normalize(mat3(modelMatrix) * normal); // Assuming no non-uniform scaling

    gl_Position = projectionMatrix * viewMatrix * worldPosition;
  }
`;

const WATER_FRAGMENT_SHADER = `
  uniform sampler2D uTexture;
  uniform bool uUseTexture; // To control texture usage
  uniform vec3 uColor;
  uniform float uOpacity;
  uniform float uTextureRepeat;

  uniform float uRoughness;
  uniform float uMetalness;

  // Caustics Uniforms
  uniform float uTime;
  uniform float uCausticsFrequency;
  uniform float uCausticsSpeed;
  uniform float uCausticsIntensity;
  uniform float uCausticsSharpness;
  uniform float uCausticsEdgeThickness;
  uniform float uCausticsDistortionFrequency; // New
  uniform float uCausticsDistortionAmplitude; // New

  varying vec2 vUv;
  varying vec3 vWorldPosition;
  varying vec3 vWorldNormal;

  // Simplex 3D noise (copied from vertex shader)
  vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
  vec4 mod289(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
  vec4 permute(vec4 x) { return mod289(((x*34.0)+1.0)*x); }
  vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.853734720909014 * r; }

  float snoise(vec3 v) {
    const vec2 C = vec2(1.0/6.0, 1.0/3.0) ;
    const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);
    vec3 i  = floor(v + dot(v, C.yyy) );
    vec3 x0 = v - i + dot(i, C.xxx) ;
    vec3 g = step(x0.yzx, x0.xyz);
    vec3 l = 1.0 - g;
    vec3 i1 = min( g.xyz, l.zxy );
    vec3 i2 = max( g.xyz, l.zxy );
    vec3 x1 = x0 - i1 + C.xxx;
    vec3 x2 = x0 - i2 + C.yyy;
    vec3 x3 = x0 - D.yyy;
    i = mod289(i);
    vec4 p = permute( permute( permute(
              i.z + vec4(0.0, i1.z, i2.z, 1.0 ))
            + i.y + vec4(0.0, i1.y, i2.y, 1.0 ))
            + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));
    float n_ = 0.142857142857; // 1.0/7.0
    vec3 ns = n_ * D.wyz - D.xzx;
    vec4 j = p - 49.0 * floor(p * ns.z * ns.z);
    vec4 x_ = floor(j * ns.z);
    vec4 y_ = floor(j - 7.0 * x_ );
    vec4 x = x_ *ns.x + ns.yyyy;
    vec4 y = y_ *ns.x + ns.yyyy;
    vec4 h = 1.0 - abs(x) - abs(y);
    vec4 b0 = vec4( x.xy, y.xy );
    vec4 b1 = vec4( x.zw, y.zw );
    vec4 s0 = floor(b0)*2.0 + 1.0;
    vec4 s1 = floor(b1)*2.0 + 1.0;
    vec4 sh = -step(h, vec4(0.0));
    vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;
    vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww ;
    vec3 p0 = vec3(a0.xy,h.x);
    vec3 p1 = vec3(a0.zw,h.y);
    vec3 p2 = vec3(a1.xy,h.z);
    vec3 p3 = vec3(a1.zw,h.w);
    vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2,p2), dot(p3,p3)));
    p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w;
    vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);
    m = m * m;
    return 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3) ) );
  }

  // Hash function to create pseudo-random vectors
  vec2 hash( vec2 p ) {
      p = vec2( dot(p,vec2(127.1,311.7)), dot(p,vec2(269.5,183.3)) );
      return -1.0 + 2.0*fract(sin(p)*43758.5453123);
  }

  // Voronoi noise function returning distance to closest (F1) and second closest (F2) points
  vec2 voronoi(vec2 x, float time) {
      vec2 p = floor(x);
      vec2 f = fract(x);
      
      float F1 = 10.0; // Initialize with a large value
      float F2 = 10.0; // Initialize with a large value

      for (int j = -1; j <= 1; j++) {
          for (int i = -1; i <= 1; i++) {
              vec2 g = vec2(float(i), float(j)); // Neighbor cell
              vec2 o = hash(p + g); // Random offset for cell center
              
              float cellTime = time + dot(p + g, vec2(0.13, 0.27)) * 10.0; // Vary animation per cell
              vec2 animatedOffset = o + vec2(sin(cellTime * 0.5), cos(cellTime * 0.3)) * 0.4; // Adjust movement

              vec2 r = g + animatedOffset - f;
              float d = dot(r,r); // Squared distance

              if (d < F1) {
                  F2 = F1;
                  F1 = d;
              } else if (d < F2) {
                  F2 = d;
              }
          }
      }
      return vec2(sqrt(F1), sqrt(F2)); // Return actual distances
  }


  void main() {
    vec3 albedo = uColor;
    if (uUseTexture) {
        vec2 repeatedUv = fract(vUv * uTextureRepeat);
        vec4 texSample = texture2D(uTexture, repeatedUv);
        albedo = mix(uColor, texSample.rgb, texSample.a * 0.6 + 0.4); 
    }

    vec3 N = normalize(vWorldNormal);
    vec3 V = normalize(cameraPosition - vWorldPosition);

    vec3 F0 = vec3(0.04); 
    F0 = mix(F0, albedo, uMetalness);

    vec3 diffuseColor = albedo * (1.0 - uMetalness); 
    
    vec3 finalColor = diffuseColor;

    // Caustics UV Distortion
    float distortionTime = uTime * 0.1; // Slower animation for distortion
    vec2 distortionOffset = vec2(
      snoise(vec3(vUv * uCausticsDistortionFrequency, distortionTime)),
      snoise(vec3(vUv * uCausticsDistortionFrequency + vec2(5.2, 1.3), distortionTime)) // Offset for second noise
    ) * uCausticsDistortionAmplitude;
    vec2 distortedUv = vUv + distortionOffset;

    // Caustics Calculation using F2-F1 for edges
    vec2 voronoiDistances = voronoi(distortedUv * uCausticsFrequency, uTime * uCausticsSpeed);
    float f1 = voronoiDistances.x;
    float f2 = voronoiDistances.y;

    float edgeFactor = f2 - f1;
    
    // Gaussian-like profile for softer lines
    float normalizedEdge = edgeFactor / uCausticsEdgeThickness;
    float causticsPattern = exp(-normalizedEdge * normalizedEdge * uCausticsSharpness);
    
    float causticsEffect = causticsPattern * uCausticsIntensity;

    finalColor.rgb += causticsEffect; // Add caustics to the final color

    gl_FragColor = vec4(finalColor, uOpacity);
  }
`;

const WaterMaterial = shaderMaterial(
  {
    // Uniforms
    uTime: 0,
    // uColor: new Color(0x1e90ff), // Default water color
    uColor: new Color("#ffffff"), // Default water color
    uTexture: null,
    uUseTexture: true,
    uOpacity: 0.84,
    uNoiseFrequency: 6.4,
    uNoiseAmplitude: 0.02,
    uNoiseSpeed: 0.5,
    uRoughness: 0.57,
    uMetalness: 0.2,
    uTextureRepeat: WATER_TEXTURE_REPEAT_MULTIPLIER,
    // Caustics uniforms
    uCausticsFrequency: 14.3,
    uCausticsSpeed: 0.16,
    uCausticsIntensity: 0.2,
    uCausticsSharpness: 1.0,
    uCausticsEdgeThickness: 0.13,
    uCausticsDistortionFrequency: 19.5,
    uCausticsDistortionAmplitude: 0.14,
  },
  WATER_VERTEX_SHADER,
  WATER_FRAGMENT_SHADER,
  (material) => {
    if (material) {
      material.transparent = true;
      material.depthWrite = false;
      // material.side = DoubleSide;
    }
  }
);

extend({ WaterMaterial });

// This component isolates the Leva controls, preventing the main component
// from re-rendering every time a control is changed.
function WaterShaderControls() {
  const controls = useControls("Water Shader", {
    noiseFrequency: { value: 4.5, min: 0.1, max: 20, step: 0.1 },
    noiseAmplitude: { value: 0.012, min: 0.001, max: 0.100, step: 0.001 },
    noiseSpeed: { value: 0.30, min: 0.0, max: 2, step: 0.01 },
    waterColor: { value: "#1e90ff", label: "Water Color" }, // Color picker
    waterOpacity: { value: 1, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0.34, min: 0, max: 1, step: 0.01 },
    metalness: { value: 0.2, min: 0, max: 1, step: 0.01 },
    useTextureFlag: { value: true, label: "Use Water Texture" },
    textureRepeat: { value: WATER_TEXTURE_REPEAT_MULTIPLIER, min: 0.1, max: 20, step: 0.1, label: "Texture Repeat" },
    causticsFrequency: {
      value: 10.0,
      min: 1,
      max: 50,
      step: 0.1,
      folder: "Caustics",
    },
    causticsSpeed: {
      value: 0.44,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      folder: "Caustics",
    },
    causticsIntensity: {
      value: 0.25,
      min: 0,
      max: 2,
      step: 0.01,
      folder: "Caustics",
    },
    causticsSharpness: {
      value: 0.02,
      min: 0.01,
      max: 10,
      step: 0.01,
      folder: "Caustics",
    },
    causticsEdgeThickness: {
      value: 0.00,
      min: 0.001,
      max: 0.5,
      step: 0.001,
      folder: "Caustics",
    },
    causticsDistortionFrequency: {
      value: 18.5,
      min: 0.1,
      max: 50,
      step: 0.1,
      folder: "Caustics",
    },
    causticsDistortionAmplitude: {
      value: 0.17,
      min: 0.0,
      max: 0.5,
      step: 0.001,
      folder: "Caustics",
    },
  }, { collapsed: true });

  return controls;
}

// Earth model controls
function EarthModelControls() {
  const controls = useControls("Earth Model", {
    // Ocean mesh controls
    oceanRotationX: { value: -0.8, min: -Math.PI, max: Math.PI, step: 0.01, folder: "Ocean" },
    oceanRotationY: { value: 0.5, min: -Math.PI, max: Math.PI, step: 0.01, folder: "Ocean" },
    oceanRotationZ: { value: -0.5, min: -Math.PI, max: Math.PI, step: 0.01, folder: "Ocean" },
    oceanScale: { value: 1.82, min: 0.1, max: 5, step: 0.01, folder: "Ocean" },

    // Inner sphere controls
    innerSphereScale: { value: 1.7, min: 0.1, max: 5, step: 0.01, folder: "Inner Sphere" },

    // Continent mesh controls
    continentPositionX: { value: 0.01, min: -2, max: 2, step: 0.001, folder: "Continent" },
    continentPositionY: { value: 0.00, min: -2, max: 2, step: 0.001, folder: "Continent" },
    continentPositionZ: { value: 0, min: -2, max: 2, step: 0.001, folder: "Continent" },
    continentRotationX: { value: -Math.PI / 2, min: -Math.PI, max: Math.PI, step: 0.01, folder: "Continent" },
    continentRotationY: { value: 0, min: -Math.PI, max: Math.PI, step: 0.01, folder: "Continent" },
    continentRotationZ: { value: -0.1, min: -Math.PI, max: Math.PI, step: 0.01, folder: "Continent" },
    continentScaleX: { value: 1.2, min: 0.1, max: 3, step: 0.001, folder: "Continent" },
    continentScaleY: { value: 1.2, min: 0.1, max: 3, step: 0.001, folder: "Continent" },
    continentScaleZ: { value: 1.2, min: 0.1, max: 3, step: 0.001, folder: "Continent" },

    // Geometry quality controls
    sphereSegments: { value: 128 * 4, min: 32, max: 512, step: 32, folder: "Geometry Quality" },
  }, { collapsed: true });

  return controls;
}

const Earth2 = forwardRef((props, ref) => {
  const { nodes, materials } = useModelLoader(localModelUrl, remoteModelUrl);

  const materialRef = useRef();
  const waterTexture = useTexture(waterTextureUrl);

  // Get controls from the separate, memoized components
  const shaderControls = WaterShaderControls();
  const modelControls = EarthModelControls();

  // Memoize the texture setup to prevent it from running on every render
  const setupTexture = useCallback(() => {
    if (waterTexture) {
      waterTexture.wrapS = waterTexture.wrapT = RepeatWrapping;
    }
  }, [waterTexture]);

  useEffect(() => {
    setupTexture();
  }, [setupTexture]);

  // Optimize the frame loop update by memoizing the callback
  const updateMaterial = useCallback((delta) => {
    if (materialRef.current) {
      materialRef.current.uniforms.uTime.value += delta;
    }
  }, []);

  useFrame((state, delta) => {
    updateMaterial(delta);
  });

  // Memoize geometry arguments to prevent re-creation on each render
  const sphereGeometryArgs = useMemo(() => [1.023, modelControls.sphereSegments, modelControls.sphereSegments], [modelControls.sphereSegments]);
  const innerSphereArgs = useMemo(() => [1.023, modelControls.sphereSegments, modelControls.sphereSegments], [modelControls.sphereSegments]);

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        name="ocean"
        rotation={[modelControls.oceanRotationX, modelControls.oceanRotationY, modelControls.oceanRotationZ]}
        scale={modelControls.oceanScale}
      >
        <sphereGeometry args={sphereGeometryArgs} />
        <waterMaterial
          ref={materialRef}
          attach="material"
          uTexture={waterTexture}
          uUseTexture={shaderControls.useTextureFlag && !!waterTexture}
          uColor={new Color(shaderControls.waterColor)}
          uOpacity={shaderControls.waterOpacity}
          uTextureRepeat={shaderControls.textureRepeat}
          uNoiseFrequency={shaderControls.noiseFrequency}
          uNoiseAmplitude={shaderControls.noiseAmplitude}
          uNoiseSpeed={shaderControls.noiseSpeed}
          uRoughness={shaderControls.roughness}
          uMetalness={shaderControls.metalness}
          uCausticsFrequency={shaderControls.causticsFrequency}
          uCausticsSpeed={shaderControls.causticsSpeed}
          uCausticsIntensity={shaderControls.causticsIntensity}
          uCausticsSharpness={shaderControls.causticsSharpness}
          uCausticsEdgeThickness={shaderControls.causticsEdgeThickness}
          uCausticsDistortionFrequency={shaderControls.causticsDistortionFrequency}
          uCausticsDistortionAmplitude={shaderControls.causticsDistortionAmplitude}
        />
      </mesh>
      <Sphere
        args={innerSphereArgs}
        position={[0, 0, 0]}
        scale={modelControls.innerSphereScale}
      />
      <mesh
        name="continent"
        geometry={nodes["optimized-verts"].geometry}
        material={materials["Material.001"]}
        position={[modelControls.continentPositionX, modelControls.continentPositionY, modelControls.continentPositionZ]}
        rotation={[modelControls.continentRotationX, modelControls.continentRotationY, modelControls.continentRotationZ]}
        scale={[modelControls.continentScaleX, modelControls.continentScaleY, modelControls.continentScaleZ]}
      />
    </group>
  );
});

preloadModel(localModelUrl, remoteModelUrl);
export default Earth2;
