/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/finger.glb --transform 
Files: ./public/finger.glb [9.66MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/index_page/cd25_website/finger-transformed.glb [220.71KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/finger-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.138, 1.32, -0.31]} rotation={[0.304, 0.042, -1.15]}>
        <mesh geometry={nodes.Armsmesh.geometry} material={materials.white} />
        <mesh geometry={nodes.Armsmesh_1.geometry} material={materials.gold} />
        <mesh geometry={nodes.Armsmesh_2.geometry} material={materials['Special Metallic Car Paint']} />
      </group>
    </group>
  )
}

useGLTF.preload('/finger-transformed.glb')
