/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Kreaton_A.glb --transform 
Files: ./public/Kreaton_A.glb [10.88MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/Kreaton_A-transformed.glb [724.45KB] (93%)
*/

import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { LoopOnce, LoopRepeat } from "three";
import {
  playAnimationTransition,
  getCurrentAnimations,
  stopAllAnimations,
  resetAnimationState,
} from "../utils/animationUtils";
import { forwardRef } from "react";
import { useImperativeHandle, useRef, useMemo, useEffect } from "react";
import { kreatonGoldMaterial } from "../materials/kreatonGoldMaterial";
import { kreatonArmorMaterial } from "../materials/kreatonWhiteArmorMaterial";
import { TextureLoader, MeshStandardMaterial, RepeatWrapping, Color } from "three";
import { useLoader } from "@react-three/fiber";
import { useModelLoader, preloadModel } from "../utils/ModelLoader";


// Define model URLs
const localModelUrl = "src/models/Kreaton_final-transformed.glb";
const remoteModelUrl = "https://files.creative-directors.com/creative-website/creative25/glbs/Kreaton_final-transformed.glb";
const DEBUG_LOGS = process.env.NODE_ENV === 'development';

const Kreaton = forwardRef((props, ref) => {
  const internalRef = useRef();
  // Use the ModelLoader utility
  const { scene, animations } = useModelLoader(localModelUrl, remoteModelUrl);
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // Load the texture
  // const skinTexture = useLoader(TextureLoader, "https://files.creative-directors.com/creative-website/creative25/textures/seamless_skin_Small.jpeg");
  // const skinTexture = useLoader(TextureLoader, "/seamless_skin_HC9.png");
  const skinTexture = useLoader(TextureLoader, "/seamless_skin_HC13.png");

  // Memoize the skin material to prevent it from being re-created on every render.
  const skinMaterial = useMemo(() => {
    if (!skinTexture) return null;

    skinTexture.wrapS = RepeatWrapping;
    skinTexture.wrapT = RepeatWrapping;
    skinTexture.needsUpdate = true;

    return new MeshStandardMaterial({
      map: skinTexture,
      roughness: 0.4,
      metalness: 0.5,
      emissiveMap: skinTexture,
      emissive: new Color("#ffffff"), // warm skin tone for emission
      emissiveIntensity: 8, //+5 on power up
    });
  }, [skinTexture]);

  // Assign our custom and memoized materials to the graph.
  // This is the correct and robust way to assign materials.
  if (skinMaterial) {
    materials.Skin = skinMaterial;
  }
  materials.gold = kreatonGoldMaterial;
  materials.white = kreatonArmorMaterial;

  const { actions, mixer } = useAnimations(animations, internalRef);

  // Define what to expose to parent components through the ref
  useImperativeHandle(ref, () => {
    const instance = {
      actions,
      getCurrentAnimation: () => {
        const playing = getCurrentAnimations(actions);
        return playing.length > 0 ? playing[0].name : null;
      },
      playAnimation: (name, options = {}) => {
        const action = actions[name];
        if (action) {
          action
            .reset()
            .fadeIn(options.fadeIn || 0.5)
            .play();
          return true;
        }
        if (DEBUG_LOGS) console.warn(`Animation "${name}" not found`);
        return false;
      },
      stopAnimation: (name, options = {}) => {
        const action = actions[name];
        if (action) {
          action.stop();
          action.fadeOut(options.fadeOut || 0.5);
          return true;
        }
        return false;
      },
      transitionAnimation: (fromName, toName, options = {}) => {
        return playAnimationTransition(
          actions,
          actions[toName],
          {
            crossFadeTime: options.crossFadeTime || 0.5,
            fadeInDuration: options.fadeInDuration || 0.2,
          },
          actions[fromName]
        );
      },
      transitionFromCurrentToAnimation: (toName, options = {}) => {
        const currentAnimationName = instance.getCurrentAnimation();
        const loopOnce = options.loopOnce || false;
        const onComplete = options.onComplete;

        if (DEBUG_LOGS) {
          console.log("Animation detection debug:");
          console.log("- Using getCurrentAnimation:", currentAnimationName);
          console.log("- Raw getCurrentAnimations:", getCurrentAnimations(actions).map((a) => a.name));
          console.log("- Animations with weight > 0:", Object.entries(actions).filter(([_, action]) => action.weight > 0).map(([name]) => `${name} (${actions[name].weight.toFixed(2)})`));
        }

        if (currentAnimationName === toName && !options.forceRestart) {
          const action = actions[toName];
          if (action && loopOnce && action.loop !== LoopOnce) {
            if (DEBUG_LOGS) console.log(`Updating loop mode for "${toName}" to LoopOnce.`);
            action.setLoop(LoopOnce, 1);
            action.clampWhenFinished = true;
            if (onComplete) {
              const listener = (event) => {
                if (event.action === action) {
                  if (DEBUG_LOGS) console.log(`LoopOnce animation "${toName}" completed.`);
                  onComplete();
                  mixer.removeEventListener("finished", listener);
                }
              };
              mixer.addEventListener("finished", listener);
            }
          } else if (action && !loopOnce && action.loop !== LoopRepeat) {
            if (DEBUG_LOGS) console.log(`Updating loop mode for "${toName}" to LoopRepeat.`);
            action.setLoop(LoopRepeat);
            action.clampWhenFinished = false;
          } else {
            if (DEBUG_LOGS) console.log(`Already playing "${toName}" animation - no transition needed`);
          }
          return true;
        }

        if (!currentAnimationName) {
          if (DEBUG_LOGS) console.log(`No current animation detected, playing: ${toName}`);
          resetAnimationState(actions);
          const action = actions[toName];
          if (action) {
            action.enabled = true;
            action.weight = 1;
            action.reset();
            if (loopOnce) {
              action.setLoop(LoopOnce, 1);
              action.clampWhenFinished = true;
              if (DEBUG_LOGS) console.log(`Playing "${toName}" once.`);
              if (onComplete) {
                const listener = (event) => {
                  if (event.action === action) {
                    if (DEBUG_LOGS) console.log(`LoopOnce animation "${toName}" completed.`);
                    onComplete();
                    mixer.removeEventListener("finished", listener);
                  }
                };
                mixer.removeEventListener("finished", listener);
                mixer.addEventListener("finished", listener);
              }
            } else {
              action.setLoop(LoopRepeat);
              action.clampWhenFinished = false;
              if (DEBUG_LOGS) console.log(`Playing "${toName}" on loop.`);
            }
            action.fadeIn(options.fadeInDuration || 0.2).play();
            return true;
          }
          if (DEBUG_LOGS) console.warn(`Animation "${toName}" not found`);
          return false;
        }

        if (DEBUG_LOGS) console.log(`Transitioning from ${currentAnimationName} to ${toName}`);
        stopAllAnimations(actions, [actions[toName], actions[currentAnimationName]], true);
        const currentAction = actions[currentAnimationName];
        const toAction = actions[toName];

        if (currentAction && toAction) {
          currentAction.fadeOut(options.crossFadeTime || 0.5);
          toAction.enabled = true;
          toAction.weight = 1;
          toAction.reset();
          if (loopOnce) {
            toAction.setLoop(LoopOnce, 1);
            toAction.clampWhenFinished = true;
            if (DEBUG_LOGS) console.log(`Transitioning to "${toName}" once.`);
            if (onComplete) {
              const listener = (event) => {
                if (event.action === toAction) {
                  if (DEBUG_LOGS) console.log(`LoopOnce animation "${toName}" completed.`);
                  onComplete();
                  mixer.removeEventListener("finished", listener);
                }
              };
              mixer.removeEventListener("finished", listener);
              mixer.addEventListener("finished", listener);
            }
          } else {
            toAction.setLoop(LoopRepeat);
            toAction.clampWhenFinished = false;
            if (DEBUG_LOGS) console.log(`Transitioning to "${toName}" on loop.`);
          }
          toAction.fadeIn(options.fadeInDuration || 0.2);
          toAction.play();
          return true;
        }

        if (DEBUG_LOGS) console.warn(`Animation transition failed: Current="${currentAnimationName}", Target="${toName}"`);
        return false;
      },
      getAnimationNames: () => Object.keys(actions),
      getObject: () => internalRef.current,
    };

    return instance;
  });

  useEffect(() => {
    if (DEBUG_LOGS) {
      console.log("Available animations:", animations);
      console.log("Available actions:", actions);
      console.log("Action keys:", Object.keys(actions));
    }
    // Hardcoded material assignments (user confirmed model will not change)
    nodes.mixamorigHips.children[0].children[0].children[0].children[0].children[0].children[1].children[2].material = skinMaterial;
    nodes.mixamorigHips.children[0].children[0].children[0].children[0].children[0].children[1].children[1].material = kreatonGoldMaterial;
    nodes.mixamorigHips.children[0].children[0].children[0].children[0].children[0].children[1].children[0].material = kreatonArmorMaterial;
    // Animation setup code...
  }, []);

  useFrame((state, delta) => {
    if (skinMaterial && skinMaterial.map) {
      skinMaterial.map.rotation += delta * 0.1;
    }
  });

  return (
    <group ref={internalRef} {...props} dispose={null}>
      <group name="Scene">
        <group name="Kreaton_Rigged">
          <primitive object={nodes.mixamorigHips} />
        </group>
        <group name="Arms001">
          <skinnedMesh
            name="Armsmesh"
            geometry={nodes.Armsmesh.geometry}
            material={materials.white}
            skeleton={nodes.Armsmesh.skeleton}
          />
          <skinnedMesh
            name="Armsmesh_1"
            geometry={nodes.Armsmesh_1.geometry}
            material={materials.gold}
            skeleton={nodes.Armsmesh_1.skeleton}
          />
          <skinnedMesh
            name="Armsmesh_2"
            geometry={nodes.Armsmesh_2.geometry}
            material={materials.Skin}
            skeleton={nodes.Armsmesh_2.skeleton}
          />
        </group>
        <group name="FeetLegs001">
          <skinnedMesh
            name="FeetLegsmesh"
            geometry={nodes.FeetLegsmesh.geometry}
            material={materials.white}
            skeleton={nodes.FeetLegsmesh.skeleton}
          />
          <skinnedMesh
            name="FeetLegsmesh_1"
            geometry={nodes.FeetLegsmesh_1.geometry}
            material={materials.gold}
            skeleton={nodes.FeetLegsmesh_1.skeleton}
          />
          <skinnedMesh
            name="FeetLegsmesh_2"
            geometry={nodes.FeetLegsmesh_2.geometry}
            material={materials.Skin}
            skeleton={nodes.FeetLegsmesh_2.skeleton}
          />
        </group>
        <group name="Skirt001">
          <skinnedMesh
            name="Skirtmesh"
            geometry={nodes.Skirtmesh.geometry}
            material={materials.white}
            skeleton={nodes.Skirtmesh.skeleton}
          />
          <skinnedMesh
            name="Skirtmesh_1"
            geometry={nodes.Skirtmesh_1.geometry}
            material={materials.gold}
            skeleton={nodes.Skirtmesh_1.skeleton}
          />
        </group>
        <group name="TorsoArmor001">
          <skinnedMesh
            name="TorsoArmormesh"
            geometry={nodes.TorsoArmormesh.geometry}
            material={materials.white}
            skeleton={nodes.TorsoArmormesh.skeleton}
          />
          <skinnedMesh
            name="TorsoArmormesh_1"
            geometry={nodes.TorsoArmormesh_1.geometry}
            material={materials.gold}
            skeleton={nodes.TorsoArmormesh_1.skeleton}
          />
          <skinnedMesh
            name="TorsoArmormesh_2"
            geometry={nodes.TorsoArmormesh_2.geometry}
            material={materials.Skin}
            skeleton={nodes.TorsoArmormesh_2.skeleton}
          />
        </group>
      </group>
    </group>
  );
});

// Preload the model
preloadModel(localModelUrl, remoteModelUrl);
export default Kreaton;
