/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/PointingFinger.glb --transform 
Files: ./public/PointingFinger.glb [9.64MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/index_page/cd25_website/PointingFinger-transformed.glb [214.75KB] (98%)
*/

import React, { useRef, forwardRef, useImperativeHandle, useEffect } from "react";
import { kreatonGoldMaterial } from "../materials/kreatonGoldMaterial";
import { kreatonArmorMaterial } from "../materials/kreatonWhiteArmorMaterial";
import { useModelLoader, preloadModel } from "../utils/ModelLoader";
import { useThree, useFrame } from "@react-three/fiber";
import { useControls, folder } from "leva";
import * as THREE from "three";

// Define model URLs
const localModelUrl = "src/models/fingerFixed-transformed.glb";
const remoteModelUrl = "https://files.creative-directors.com/creative-website/creative25/glbs/fingerFixed-transformed.glb";

export const PointingFinger = forwardRef((props, ref) => {
  const internalRef = useRef();
  const { nodes, materials } = useModelLoader(localModelUrl, remoteModelUrl);
  const { camera, size } = useThree();
  const mouse = useRef(new THREE.Vector2());
  const targetPosition = useRef(new THREE.Vector3());

  // Controls for anchor point position and movement limits
  const controls = useControls({
    'Anchor Point': folder({
      anchorX: { value: 0, min: -2, max: 2, step: 0.1 },
      anchorY: { value: 1.32, min: -2, max: 2, step: 0.1 },
      anchorZ: { value: -0.31, min: -2, max: 2, step: 0.1 },
    }),
    'Movement Limits': folder({
      // Rotation limits in degrees
      minRotationX: { value: -45, min: -180, max: 180, step: 1 },
      maxRotationX: { value: 45, min: -180, max: 180, step: 1 },
      minRotationY: { value: -45, min: -180, max: 180, step: 1 },
      maxRotationY: { value: 45, min: -180, max: 180, step: 1 },
      minRotationZ: { value: -45, min: -180, max: 180, step: 1 },
      maxRotationZ: { value: 45, min: -180, max: 180, step: 1 },
      // Position limits
      minX: { value: -1, min: -5, max: 5, step: 0.1 },
      maxX: { value: 1, min: -5, max: 5, step: 0.1 },
      minY: { value: -1, min: -5, max: 5, step: 0.1 },
      maxY: { value: 1, min: -5, max: 5, step: 0.1 },
      minZ: { value: -1, min: -5, max: 5, step: 0.1 },
      maxZ: { value: 1, min: -5, max: 5, step: 0.1 },
    }),
    'Movement Settings': folder({
      smoothing: { value: 0.1, min: 0, max: 1, step: 0.01 },
      enabled: { value: true },
      planeDistance: { value: 20, min: 1, max: 50, step: 1, label: "Plane Distance (Z)" },
    }),
    'Direction Offset': folder({
      dirOffsetX: { value: 0, min: -1, max: 1, step: 0.01 },
      dirOffsetY: { value: 0, min: -1, max: 1, step: 0.01 },
      dirOffsetZ: { value: 0, min: -1, max: 1, step: 0.01 },
    })
  }, { collapsed: true });

  materials.gold = kreatonGoldMaterial;
  materials.white = kreatonArmorMaterial;

  // Handle mouse movement
  useEffect(() => {
    const handleMouseMove = (event) => {
      if (!controls.enabled) return;
      mouse.current.x = (event.clientX / size.width) * 2 - 1;
      mouse.current.y = -(event.clientY / size.height) * 2 + 1;
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, [size, controls.enabled]);

  // Helper function to clamp a value between min and max
  const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

  // Helper function to convert degrees to radians
  const degToRad = (degrees) => degrees * (Math.PI / 180);

  // Update finger position to follow mouse
  useFrame(() => {
    if (!internalRef.current || !controls.enabled) return;

    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(mouse.current, camera);

    // Create a plane at the specified distance in Z direction
    const plane = new THREE.Plane(new THREE.Vector3(0, 0, 1), -controls.planeDistance);
    const intersectionPoint = new THREE.Vector3();

    if (raycaster.ray.intersectPlane(plane, intersectionPoint)) {
      const anchorPoint = new THREE.Vector3(
        controls.anchorX,
        controls.anchorY,
        controls.anchorZ
      );
      let direction = intersectionPoint.sub(anchorPoint).normalize();
      // Apply direction offset from controls
      direction.x += controls.dirOffsetX;
      direction.y += controls.dirOffsetY;
      direction.z += controls.dirOffsetZ;
      direction.normalize();

      // Calculate rotation
      const rotation = new THREE.Euler();
      rotation.setFromQuaternion(
        new THREE.Quaternion().setFromUnitVectors(
          new THREE.Vector3(0, 0, 1),
          direction
        )
      );

      // Convert rotation to degrees for clamping
      const currentRotationX = THREE.MathUtils.radToDeg(rotation.x);
      const currentRotationY = THREE.MathUtils.radToDeg(rotation.y);
      const currentRotationZ = THREE.MathUtils.radToDeg(rotation.z);

      // Clamp rotations
      const clampedRotationX = clamp(currentRotationX, controls.minRotationX, controls.maxRotationX);
      const clampedRotationY = clamp(currentRotationY, controls.minRotationY, controls.maxRotationY);
      const clampedRotationZ = clamp(currentRotationZ, controls.minRotationZ, controls.maxRotationZ);

      // Convert back to radians and apply with smoothing
      const targetRotationX = degToRad(clampedRotationX);
      const targetRotationY = degToRad(clampedRotationY);
      const targetRotationZ = degToRad(clampedRotationZ);

      // Apply smoothed rotation
      internalRef.current.rotation.x += (targetRotationX - internalRef.current.rotation.x) * controls.smoothing;
      internalRef.current.rotation.y += (targetRotationY - internalRef.current.rotation.y) * controls.smoothing;
      internalRef.current.rotation.z += (targetRotationZ - internalRef.current.rotation.z) * controls.smoothing;

      // Clamp position
      // const currentPosition = internalRef.current.position;
      // currentPosition.x = clamp(currentPosition.x, controls.minX, controls.maxX);
      // currentPosition.y = clamp(currentPosition.y, controls.minY, controls.maxY);
      // currentPosition.z = clamp(currentPosition.z, controls.minZ, controls.maxZ);

    }
  });

  // Expose the internal ref to the parent component
  useImperativeHandle(ref, () => internalRef.current);

  return (
    <group {...props} dispose={null}>
      <group
        ref={internalRef}
        position={[controls.anchorX, controls.anchorY, controls.anchorZ]}
      >
        <mesh geometry={nodes.Armsmesh.geometry} material={materials.white} />
        <mesh geometry={nodes.Armsmesh_1.geometry} material={materials.gold} />
        <mesh geometry={nodes.Armsmesh_2.geometry} />
        <mesh geometry={nodes.Armsmesh_3.geometry} />
      </group>
    </group>
  );
});

preloadModel(localModelUrl, remoteModelUrl);
