/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/KreatonUV2.glb --transform 
Files: ./public/KreatonUV2.glb [10.76MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/KreatonUV2-transformed.glb [708.79KB] (93%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/KreatonUV2-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Kreaton_Rigged">
          <primitive object={nodes.mixamorigHips} />
        </group>
        <group name="Arms001">
          <skinnedMesh name="Armsmesh" geometry={nodes.Armsmesh.geometry} material={materials.white} skeleton={nodes.Armsmesh.skeleton} />
          <skinnedMesh name="Armsmesh_1" geometry={nodes.Armsmesh_1.geometry} material={materials.gold} skeleton={nodes.Armsmesh_1.skeleton} />
          <skinnedMesh name="Armsmesh_2" geometry={nodes.Armsmesh_2.geometry} material={materials.Skin} skeleton={nodes.Armsmesh_2.skeleton} />
        </group>
        <group name="FeetLegs001">
          <skinnedMesh name="FeetLegsmesh" geometry={nodes.FeetLegsmesh.geometry} material={materials.white} skeleton={nodes.FeetLegsmesh.skeleton} />
          <skinnedMesh name="FeetLegsmesh_1" geometry={nodes.FeetLegsmesh_1.geometry} material={materials.gold} skeleton={nodes.FeetLegsmesh_1.skeleton} />
          <skinnedMesh name="FeetLegsmesh_2" geometry={nodes.FeetLegsmesh_2.geometry} material={materials.Skin} skeleton={nodes.FeetLegsmesh_2.skeleton} />
        </group>
        <group name="Skirt001">
          <skinnedMesh name="Skirtmesh" geometry={nodes.Skirtmesh.geometry} material={materials.white} skeleton={nodes.Skirtmesh.skeleton} />
          <skinnedMesh name="Skirtmesh_1" geometry={nodes.Skirtmesh_1.geometry} material={materials.gold} skeleton={nodes.Skirtmesh_1.skeleton} />
        </group>
        <group name="TorsoArmor001">
          <skinnedMesh name="TorsoArmormesh" geometry={nodes.TorsoArmormesh.geometry} material={materials.white} skeleton={nodes.TorsoArmormesh.skeleton} />
          <skinnedMesh name="TorsoArmormesh_1" geometry={nodes.TorsoArmormesh_1.geometry} material={materials.gold} skeleton={nodes.TorsoArmormesh_1.skeleton} />
          <skinnedMesh name="TorsoArmormesh_2" geometry={nodes.TorsoArmormesh_2.geometry} material={materials.Skin} skeleton={nodes.TorsoArmormesh_2.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/KreatonUV2-transformed.glb')
